ObligatorioP3/Models/AltaEnvioViewModel.cs
using Libreria.DTOs.DTOs.DTOsEnvio;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ObligatorioP3.Models
{
    public class AltaEnvioViewModel
    {
        public DTOAltaEnvio dtoAltaEnvio { get; set; }
        public List<SelectListItem> Clientes { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> Agencias { get; set; } = new List<SelectListItem>();
    }
}

ObligatorioP3/Models/ModificarUsuarioViewModel.cs
using Libreria.DTOs.DTOs.DTOsUsuario;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ObligatorioP3.Models
{
    public class ModificarUsuarioViewModel
    {
        public DTOUsuario Usuario { get; set; }

        public List<SelectListItem> Roles { get; set; } = new List<SelectListItem>() {
         new SelectListItem{ Text ="Administrador", Value="Administrador" },
         new SelectListItem{ Text ="Funcionario", Value="Funcionario" },
         new SelectListItem{ Text ="Cliente", Value="Cliente" }

        };

    }
}

ObligatorioP3/Models/NuevoSeguimientoViewModel.cs
using Libreria.DTOs.DTOs.DTOsEnvio;
using Libreria.DTOs.DTOs.DTOsSeguimientoEnvio;

namespace ObligatorioP3.Models
{
    public class NuevoSeguimientoViewModel
    {

        public DTOSeguimientoEnvio Seguimiento { get; set; }
        public DTOEnvio Envio { get; set; }


    }
}

ObligatorioP3/Controllers/EnvioController.cs
using Libreria.DTOs.DTOs.DTOsAgencia;
using Libreria.DTOs.DTOs.DTOsEnvio;
using Libreria.DTOs.DTOs.DTOsUsuario;
using Libreria.LogicaAplicacion.InterfacesCasosUso.ICUAgencia;
using Libreria.LogicaAplicacion.InterfacesCasosUso.ICUEnvios;
using Libreria.LogicaAplicacion.InterfacesCasosUso.ICUSeguimiento;
using Libreria.LogicaAplicacion.InterfacesCasosUso.ICUUsuario;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ObligatorioP3.Filters;
using ObligatorioP3.Models;

namespace ObligatorioP3.Controllers
{
    public class EnvioController : Controller
    {

        private ICUAltaEnvio _cuAltaEnvio;
        private ICUListarEnvio _cuListarEnvio;
        private ICUFinalizarEnvio _cuFinalizarEnvio;
        private ICUListarUsuario _cuListarUsuario;
        private ICUListarAgencia _cuListarAgencia;
        private ICUAgregarSeguimiento _cuAgregarSeguimiento;


        public EnvioController(ICUAltaEnvio cuAltaEnvio, ICUListarEnvio cuListarEnvio, ICUFinalizarEnvio cuFinalizarEnvio, ICUListarUsuario cuListarUsuario, ICUListarAgencia cuListarAgencia, ICUAgregarSeguimiento cuAgregarSeguimiento)
        {
            _cuAltaEnvio = cuAltaEnvio;
            _cuListarEnvio = cuListarEnvio;
            _cuFinalizarEnvio = cuFinalizarEnvio;
            _cuListarUsuario = cuListarUsuario;
            _cuListarAgencia = cuListarAgencia;
            _cuAgregarSeguimiento = cuAgregarSeguimiento;
        }

        [FuncionarioAuthorize]
        public IActionResult Index()
        {
            try
            {
                List<DTOEnvio> envios = _cuListarEnvio.ListarEnvios();
                return View(envios);
            }
            catch (Exception e)
            {
                ViewBag.Mensaje = e.Message;
                return View();
            }
        }

        [FuncionarioAuthorize]
        public IActionResult AltaEnvio()
        {
            List<DTOUsuario> clientes = _cuListarUsuario.ListarUsuario();
            List<DTOAgencia> agencias = _cuListarAgencia.ListarAgencia();

            AltaEnvioViewModel viewModel = new AltaEnvioViewModel();

            foreach (DTOUsuario cli in clientes)
            {
                SelectListItem sitem = new SelectListItem();
                sitem.Text = cli.Email;
                sitem.Value = cli.Id.ToString();
                viewModel.Clientes.Add(sitem);
            }

            foreach (DTOAgencia ag in agencias)
            {
                SelectListItem sitem = new SelectListItem();
                sitem.Text = ag.Nombre;
                sitem.Value = ag.Id.ToString();
                viewModel.Agencias.Add(sitem);
            }

            return View(viewModel);
        }

        [HttpPost]
        [FuncionarioAuthorize]
        public IActionResult AltaEnvio(AltaEnvioViewModel viewModel)
        {
            try
            {
                viewModel.dtoAltaEnvio.LogueadoId = HttpContext.Session.GetInt32("LogueadoID");

                _cuAltaEnvio.AltaEnvio(viewModel.dtoAltaEnvio);
                TempData["Mensaje"] = "Envío creado correctamente";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["Error"] = e.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [FuncionarioAuthorize]
        public IActionResult FinalizarEnvio(int id)
        {
            try
            {
                int logueadoId = (int)HttpContext.Session.GetInt32("LogueadoID");
                _cuFinalizarEnvio.FinalizarEnvio(id, logueadoId);
                TempData["Mensaje"] = "Envio finalizado correctamente.";
            }
            catch (Exception e)
            {
                TempData["Error"] = e.Message;
            }
            return RedirectToAction("Index");
        }

        [FuncionarioAuthorize]
        public IActionResult NuevoSeguimiento(int id)
        {
            try
            {

                NuevoSeguimientoViewModel viewModel = new NuevoSeguimientoViewModel();

                viewModel.Envio = _cuListarEnvio.ListarEnvioPorId(id);

                return View(viewModel);
            }
            catch (Exception e)
            {
                ViewBag.Mensaje = e.Message;
                return View();
            }
        }

        [HttpPost]
        [FuncionarioAuthorize]
        public IActionResult NuevoSeguimiento(NuevoSeguimientoViewModel viewModel)
        {
            try
            {

                viewModel.Seguimiento.IdEmpleado = (int)HttpContext.Session.GetInt32("LogueadoID");
                viewModel.Seguimiento.EnvioId = viewModel.Envio.Id;

                _cuAgregarSeguimiento.AgregarSeguimiento(viewModel.Seguimiento);

                TempData["Mensaje"] = "Seguimiento creado correctamente";

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["Error"] = e.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

ObligatorioP3/Controllers/UsuarioController.cs
using Libreria.DTOs.DTOs.DTOsUsuario;
using Libreria.LogicaAplicacion.InterfacesCasosUso.ICUAutenticacion;
using Libreria.LogicaAplicacion.InterfacesCasosUso.ICUUsuario;
using Libreria.LogicaNegocio.CustomExceptions.UsuarioExceptions;
using Microsoft.AspNetCore.Mvc;
using ObligatorioP3.Filters;
using ObligatorioP3.Models;

namespace ObligatorioP3.Controllers
{
    public class UsuarioController : Controller
    {

        private ICUAltaUsuario _cuAltaUsuario;
        private ICUListarUsuario _cuListarUsuario;
        private ICUEditarUsuario _cuEditarUsuario;
        private ICUEliminarUsuario _cuEliminarUsuario;
        private ICULogin _cuLogin;

        public UsuarioController(ICULogin cuLogin, ICUAltaUsuario cuAltaUsuario, ICUListarUsuario cuListarUsuario, ICUEditarUsuario cuEditarUsuario, ICUEliminarUsuario cuEliminarUsuario)
        {
            _cuAltaUsuario = cuAltaUsuario;
            _cuListarUsuario = cuListarUsuario;
            _cuEditarUsuario = cuEditarUsuario;
            _cuEliminarUsuario = cuEliminarUsuario;
            _cuLogin = cuLogin;

        }

        [FuncionarioAuthorize]
        public IActionResult Index()
        {
            return View();
        }

        [AdminAuthorize]
        public IActionResult AltaUsuario()
        {
            try
            {

                CrearUsuarioViewModel viewModel = new CrearUsuarioViewModel();

                return View(viewModel);
            }
            catch (Exception e)
            {
                ViewBag.Mensaje = e.Message;
                return View();
            }
        }

        [AdminAuthorize]
        [HttpPost]
        public IActionResult AltaUsuario(CrearUsuarioViewModel viewModel)
        {

            try
            {
                viewModel.Usuario.LogueadoId = (int)HttpContext.Session.GetInt32("LogueadoID");

                _cuAltaUsuario.AltaUsuario(viewModel.Usuario);

                TempData["Mensaje"] = "Usuario creado correctamente";

                return RedirectToAction("MostrarUsuarios");

            }

            catch (ApellidoNoValidoException e)
            {
                TempData["Error"] = e.Message;

                return RedirectToAction("Index");
            }
            catch (EmailNoValidoException e)
            {
                TempData["Error"] = e.Message;

                return RedirectToAction("Index");
            }
            catch (NombreNoValidoException e)
            {
                TempData["Error"] = e.Message;

                return RedirectToAction("Index");
            }
            catch (PasswordNoValidoException e)
            {
                TempData["Error"] = e.Message;

                return RedirectToAction("Index");
            }
            catch (RolNoValidoException e)
            {
                TempData["Error"] = e.Message;

                return RedirectToAction("Index");
            }
            catch (UsuarioExisteException e)
            {
                TempData["Error"] = e.Message;

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["Error"] = e.Message;

                return RedirectToAction("Index");
            }

        }

        [AdminAuthorize]
        public IActionResult MostrarUsuarios()
        {
            try
            {
                List<DTOUsuario> usuarios = _cuListarUsuario.ListarUsuario();
                return View(usuarios);
            }
            catch (Exception e)
            {
                ViewBag.Mensaje = e.Message;
                return View();
            }
        }

        [AdminAuthorize]
        public IActionResult ModificarUsuario(int id)
        {
            try
            {

                ModificarUsuarioViewModel viewModel = new ModificarUsuarioViewModel();

                viewModel.Usuario = _cuListarUsuario.ListarUsuarioPorId(id);

                return View(viewModel);
            }
            catch (Exception e)
            {
                ViewBag.Mensaje = e.Message;
                return View();
            }
        }

        [HttpPost]
        [AdminAuthorize]
        public IActionResult ModificarUsuario(ModificarUsuarioViewModel viewModel)
        {
            try
            {
                viewModel.Usuario.LogueadoId = (int)HttpContext.Session.GetInt32("LogueadoID");

                _cuEditarUsuario.EditarUsuario(viewModel.Usuario);

                TempData["Mensaje"] = "Usuario modificado correctamente";

                return RedirectToAction("MostrarUsuarios");

            }
            catch (Exception e)
            {
                TempData["Error"] = e.Message;
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        [AdminAuthorize]
        public IActionResult EliminarUsuario(int id)
        {
            try
            {
                int logueadoId = (int)HttpContext.Session.GetInt32("LogueadoID");
                _cuEliminarUsuario.EliminarUsuario(id, logueadoId);
                TempData["Mensaje"] = "Usuario eliminado correctamente.";
            }
            catch (Exception e)
            {
                TempData["Error"] = e.Message;
            }
            return RedirectToAction("MostrarUsuarios");
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(DTOUsuario dtoUsuario)
        {
            try
            {
                HttpContext.Session.Clear();

                DTOUsuario u = _cuLogin.ValidarLogin(dtoUsuario);

                if (u.Rol == "Cliente")
                {
                    ViewBag.Mensaje = "Acceso denegado para clientes.";
                    return View();
                }

                HttpContext.Session.SetInt32("LogueadoID", (int)u.Id);
                HttpContext.Session.SetString("LogueadoRol", u.Rol);

                return RedirectToAction("Index", "Usuario");
            }
            catch (Exception e)
            {
                ViewBag.Mensaje = e.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

    }
}

ObligatorioP3/Views/Usuario/AltaEnvio.cshtml
@model ObligatorioP3.Models.AltaEnvioViewModel

@{
    ViewData["Title"] = "Alta Envio";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Crear Envío</h3>
                </div>
                <div class="card-body">
                    <form asp-action="AltaEnvio" autocomplete="off">
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="mb-3">
                            <label class="form-label">Cliente</label>
                            <select asp-for="dtoAltaEnvio.ClienteId" asp-items="Model.Clientes" class="form-control">
                                <option value="">Seleccione un cliente</option>
                            </select>
                            <span asp-validation-for="dtoAltaEnvio.ClienteId" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Peso (en kg)</label>
                            <input asp-for="dtoAltaEnvio.Peso" class="form-control" />
                            <span asp-validation-for="dtoAltaEnvio.Peso" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Tipo de Envío</label>
                            <select asp-for="dtoAltaEnvio.TipoEnvio" class="form-control" onchange="toggleFields()">
                                <option value="">Seleccione una opción</option>
                                <option value="comun">Envio Comun</option>
                                <option value="urgente">Envio Urgente</option>
                            </select>
                            <span asp-validation-for="dtoAltaEnvio.TipoEnvio" class="text-danger"></span>
                        </div>
                        <div id="comunFields" style="display: none;">
                            <div class="mb-3">
                                <label class="form-label">Agencia Destino</label>
                                <select asp-for="dtoAltaEnvio.AgenciaDestinoId" asp-items="Model.Agencias" class="form-control">
                                    <option value="">Seleccione una agencia</option>
                                </select>
                                <span asp-validation-for="dtoAltaEnvio.AgenciaDestinoId" class="text-danger"></span>
                            </div>
                        </div>
                        <div id="urgenteFields" style="display: none;">
                            <div class="mb-3">
                                <label class="form-label">Calle</label>
                                <input asp-for="dtoAltaEnvio.Calle" class="form-control" />
                                <span asp-validation-for="dtoAltaEnvio.Calle" class="text-danger"></span>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Número de Puerta</label>
                                <input asp-for="dtoAltaEnvio.NroPuerta" class="form-control" />
                                <span asp-validation-for="dtoAltaEnvio.NroPuerta" class="text-danger"></span>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Departamento</label>
                                <input asp-for="dtoAltaEnvio.Departamento" class="form-control" />
                                <span asp-validation-for="dtoAltaEnvio.Departamento" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between">
                            <a asp-action="Index" class="btn btn-outline-secondary">
                                <i class="bi bi-arrow-left"></i> Volver
                            </a>
                            <button type="submit" class="btn btn-success">
                                <i class="bi bi-plus-circle"></i> Crear Envío
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function toggleFields() {
            const tipoEnvio = document.getElementById("dtoAltaEnvio_TipoEnvio").value;
            document.getElementById("comunFields").style.display = tipoEnvio === "comun" ? "block" : "none";
            document.getElementById("urgenteFields").style.display = tipoEnvio === "urgente" ? "block" : "none";
        }
        document.addEventListener("DOMContentLoaded", function () {
            toggleFields();
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ObligatorioP3/Views/Usuario/AltaUsuario.cshtml
@model ObligatorioP3.Models.CrearUsuarioViewModel

@{
    ViewData["Title"] = "Alta Usuario";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Crear Usuario</h3>
                </div>
                <div class="card-body">
                    <form asp-action="AltaUsuario" autocomplete="off">
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Nombre" class="form-label"></label>
                            <input asp-for="Usuario.Nombre" class="form-control" />
                            <span asp-validation-for="Usuario.Nombre" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Apellido" class="form-label"></label>
                            <input asp-for="Usuario.Apellido" class="form-control" />
                            <span asp-validation-for="Usuario.Apellido" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Email" class="form-label"></label>
                            <input asp-for="Usuario.Email" class="form-control" />
                            <span asp-validation-for="Usuario.Email" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Password" class="form-label"></label>
                            <input asp-for="Usuario.Password" type="password" class="form-control" required />
                            <span asp-validation-for="Usuario.Password" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Rol" class="form-label"></label>
                            <select asp-for="Usuario.Rol" class="form-control" asp-items="Model.Roles" required>
                                <option value="">Seleccione un rol</option>
                            </select>
                            <span asp-validation-for="Usuario.Rol" class="text-danger"></span>
                        </div>
                        <div class="d-flex justify-content-between">
                            <a asp-action="Index" class="btn btn-outline-secondary">
                                <i class="bi bi-arrow-left"></i> Volver
                            </a>
                            <button type="submit" class="btn btn-success">
                                <i class="bi bi-plus-circle"></i> Crear Usuario
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ObligatorioP3/Views/Usuario/Index.cshtml
@{
    ViewData["Title"] = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userRole = Context.Session.GetString("LogueadoRol");
}

@if (TempData["Mensaje"] != null)
{
    <div class="alert alert-success text-center">
        @TempData["Mensaje"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger text-center">
        @TempData["Error"]
    </div>
}

<div class="container mt-5">
    <div class="row mb-4">
        <div class="col-12 d-flex justify-content-center">
            <h1 class="fw-bold text-primary">Dashboard</h1>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 d-flex flex-wrap justify-content-center gap-3">

            @if (userRole == "Administrador")
            {
                <a href="@Url.Action("MostrarUsuarios", "Usuario")" class="btn btn-primary btn-square btn-md d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-list fs-3"></i>
                    <span class="mt-1">Listar Usuarios</span>
                </a>
            }

            @if (userRole == "Administrador")
            {
                <a href="@Url.Action("AltaUsuario", "Usuario")" class="btn btn-success btn-square btn-md d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-person-plus fs-3"></i>
                    <span class="mt-1">Agregar Usuarios</span>
                </a>
            }

            @if (userRole == "Administrador" || userRole == "Funcionario")
            {
                <a href="@Url.Action("AltaEnvio", "Envio")" class="btn btn-info btn-square btn-md d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-box fs-3"></i>
                    <span class="mt-1">Alta Envío</span>
                </a>
            }

            @if (userRole == "Administrador" || userRole == "Funcionario")
            {
                <a href="@Url.Action("Index", "Envio")" class="btn btn-warning btn-square btn-md d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-truck fs-3"></i>
                    <span class="mt-1">Mostrar Envíos</span>
                </a>
            }

            <form asp-action="Logout" asp-controller="Usuario" method="post" class="m-0">
                <button type="submit" class="btn btn-danger btn-square btn-md d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-box-arrow-right fs-3"></i>
                    <span class="mt-1">Cerrar Sesión</span>
                </button>
            </form>
        </div>
    </div>
</div>

<style>
    .btn-square {
        width: 120px;
        height: 120px;
        padding: 0;
        border-radius: 12px !important;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        transition: transform 0.1s;
    }
    .btn-square:hover {
        transform: scale(1.05);
        z-index: 2;
    }
    .btn-md {
        font-size: 1rem;
    }
</style>

ObligatorioP3/Views/Usuario/Login.cshtml
@model Libreria.DTOs.DTOs.DTOsUsuario.DTOUsuario

@{
    ViewData["Title"] = "Login";
}

<div class="container vh-100 d-flex align-items-center justify-content-center">
    <div class="row w-100 justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-lg border-0 rounded-3">
                <div class="card-header bg-primary text-white text-center">
                    <h2 class="mb-0">Iniciar Sesión</h2>
                </div>
                <div class="card-body">
                    @if (ViewBag.Mensaje != null)
                    {
                        <div class="alert alert-info text-center">
                            @ViewBag.Mensaje
                        </div>
                    }
                    <form asp-action="Login" autocomplete="off">
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="form-group mb-3">
                            <label asp-for="Email" class="form-label"></label>
                            <input asp-for="Email" class="form-control" placeholder="Correo electrónico" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-4">
                            <label asp-for="Password" class="form-label"></label>
                            <input asp-for="Password" class="form-control" placeholder="Contraseña" type="password" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                    </form>
                    <div class="d-grid mt-2">
                        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary btn-block">Volver</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ObligatorioP3/Views/Usuario/ModificarUsuario.cshtml
@model ObligatorioP3.Models.ModificarUsuarioViewModel

@{
    ViewData["Title"] = "Modificar Usuario";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Modificar Usuario</h3>
                </div>
                <div class="card-body">
                    
                    <form asp-action="ModificarUsuario" autocomplete="off">
                        <input type="hidden" asp-for="Usuario.Id" />
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Nombre" class="form-label"></label>
                            <input asp-for="Usuario.Nombre" class="form-control" />
                            <span asp-validation-for="Usuario.Nombre" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Apellido" class="form-label"></label>
                            <input asp-for="Usuario.Apellido" class="form-control" />
                            <span asp-validation-for="Usuario.Apellido" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Email" class="form-label"></label>
                            <input asp-for="Usuario.Email" class="form-control" />
                            <span asp-validation-for="Usuario.Email" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Usuario.Rol" class="form-label"></label>
                            <select asp-for="Usuario.Rol" class="form-select" asp-items="Model.Roles">
                            </select>
                            <span asp-validation-for="Usuario.Rol" class="text-danger"></span>
                        </div>
                        <div class="d-flex justify-content-between">
                            <a asp-controller="Usuario" asp-action="MostrarUsuarios" class="btn btn-outline-secondary">
                                <i class="bi bi-arrow-left"></i> Volver a la lista
                            </a>
                            <button type="submit" class="btn btn-success">
                                <i class="bi bi-save"></i> Guardar Cambios
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ObligatorioP3/Views/Usuario/NuevoSeguimiento.cshtml
@model ObligatorioP3.Models.NuevoSeguimientoViewModel

@{
    ViewData["Title"] = "Nuevo Seguimiento";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7 col-lg-6">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0"><i class="bi bi-plus-circle"></i> Nuevo Seguimiento</h3>
                </div>
                <div class="card-body">
                    <form asp-action="NuevoSeguimiento">
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                        <input type="hidden" asp-for="Envio.Id" value="@Model.Envio.Id" />

                        <div class="mb-3">
                            <label asp-for="Seguimiento.Comentario" class="form-label"></label>
                            <textarea asp-for="Seguimiento.Comentario" class="form-control" rows="4" placeholder="Ingrese un comentario..."></textarea>
                            <span asp-validation-for="Seguimiento.Comentario" class="text-danger"></span>
                        </div>

                        <div class="d-flex justify-content-between">
                            <a asp-action="MostrarEnvios" class="btn btn-outline-secondary">
                                <i class="bi bi-arrow-left"></i> Volver a la lista
                            </a>
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-check-circle"></i> Crear
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}